### ISSUE TITLE
Batch Generation Index problem

### ISSUE THREAD

**Issue by mumtazv** [pierluigiferrari/fcn8s_tensorflow#1]
IndexError                                Traceback (most recent call last)
<ipython-input-16-a9a22fb1365b> in <module>()
      1 # Print out some diagnostics to make sure that our batches aren't empty and it doesn't take 
Hi, 

Getting this issue when running the code below.  Some batch generation is failing somewhere. 
Can you please let me know.  I am running on cityscapes dataset, following your tutorial. 

Thanks. 
Taz

Print out some diagnostics to make sure that our batches aren't empty and it doesn't take forever to generate them.
start_time = time.time()
images, gt_images = next(train_generator)
print('Time to generate one batch: {:.3f} seconds'.format(time.time() - start_time))
print('Number of images generated:' , len(images))
print('Number of ground truth images generated:' , len(gt_images))

      2 start_time = time.time()
----> 3 images, gt_images = next(train_generator)
      4 print('Time to generate one batch: {:.3f} seconds'.format(time.time() - start_time))
      5 print('Number of images generated:' , len(images))

~/fcn8s_tensorflow/data_generator/batch_generator.py in generate(self, batch_size, convert_colors_to_ids, convert_ids_to_ids, convert_to_one_hot, void_class_id, random_crop, crop, resize, brightness, flip, translate, scale, gray, to_disk, shuffle)
    389                 # Maybe convert ground truth IDs to one-hot.
    390                 if convert_to_one_hot:
--> 391                     gt_image = convert_IDs_to_one_hot(gt_image, self.num_classes)
    392 
    393                 if to_disk: # If the processed data is to be written to disk instead of yieled.

~/fcn8s_tensorflow/helpers/ground_truth_conversion_utils.py in convert_IDs_to_one_hot(image, num_classes)
     86     unity_vectors = np.eye(num_classes, dtype=np.bool)
     87 
---> 88     return unity_vectors[image]

IndexError: index 23 is out of bounds for axis 0 with size 20

**Comment by mumtazv** [comment]
Resolved the issue.....

**Comment by shiyihan** [comment]
hello，I have the same problem as you.Could you tell me how you solved this issue?
