### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by ErlendFax** [pierluigiferrari/fcn8s_tensorflow#3]
First of, great work.

I'm fiddling around with different input shapes on the pre-trained VGG-16, but can't really get a hold of what shape it excepts...

Doesn't VGG-16 need a 224 x 224 input shape?

What happens when the input shape is different?

**Comment by pierluigiferrari** [comment]
The original VGG-16 does require a certain fixed input size because of the fully connected layers, but this is a fully convolutional version, so it works with any input size.
